<?php

declare(strict_types=1);

namespace App\Services\MailClient;

/**
 * A message the employee is sending — reply or fresh compose (plan B5a).
 *
 * Immutable so it can be built once (by the composer, B5b) and carried through
 * the queue to {@see \App\Jobs\SendUserEmail} unchanged. `messageId`,
 * `inReplyTo` and `references` are the RFC 5322 threading headers: setting them
 * on a reply is what makes it land in the recipient's existing conversation and
 * lets our own re-sync dedupe the sent copy. All ids are stored WITH angle
 * brackets (`<id@host>`); the mailable/store normalise as needed.
 */
final class OutboundEmail
{
    /**
     * @param  list<string>  $to
     * @param  list<string>  $cc
     * @param  list<string>  $bcc
     * @param  list<OutboundAttachment>  $attachments
     */
    public function __construct(
        public readonly array $to,
        public readonly string $subject,
        public readonly ?string $bodyHtml = null,
        public readonly ?string $bodyText = null,
        public readonly array $cc = [],
        public readonly array $bcc = [],
        public readonly ?string $inReplyTo = null,
        public readonly ?string $references = null,
        public readonly ?int $threadId = null,
        public readonly ?string $messageId = null,
        public readonly array $attachments = [],
    ) {}

    /**
     * Rebuild with a stamped Message-ID (generated by the send job so the sent
     * header and the stored copy match exactly).
     */
    public function withMessageId(string $messageId): self
    {
        return new self(
            to: $this->to,
            subject: $this->subject,
            bodyHtml: $this->bodyHtml,
            bodyText: $this->bodyText,
            cc: $this->cc,
            bcc: $this->bcc,
            inReplyTo: $this->inReplyTo,
            references: $this->references,
            threadId: $this->threadId,
            messageId: $messageId,
            attachments: $this->attachments,
        );
    }

    public function hasAttachments(): bool
    {
        return $this->attachments !== [];
    }
}
